# Generated by Django 3.2.11 on 2022-01-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.IntegerField()),
                ('tv_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rack', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
